#!/usr/bin/env node
// Emits supabase/functions/_shared/catalogue.ts from out/catalogue.json.
// Vehicles only (models → grades → prices/colours) — spare parts stay out so
// part prices can never leak into car quotes. Rerun after every scrape:
//   node tools/catalogue/emit-module.mjs

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const raw = JSON.parse(readFileSync(join(here, "out", "catalogue.json"), "utf8"));

const models = raw.models.map((m) => ({
  id: m.id,
  name: m.name,
  year: m.year ?? null,
  starting_price_incl_vat_sar: m.starting_price_incl_vat_sar ?? null,
  grades: (m.grades ?? []).map((g) => ({
    id: g.id,
    name_en: g.name_en ?? null,
    name_ar: g.name_ar ?? null,
    price_incl_vat_sar: g.price_incl_vat_sar ?? null,
    price_ex_vat_sar: g.price_ex_vat_sar ?? null,
    colours: (g.colours ?? []).map((c) => c.name_ar),
  })),
}));

const out = `// GENERATED by tools/catalogue/emit-module.mjs — do not edit.
// Source: changan-ksa.com scrape ${raw.source.scraped_at}. Vehicles only.
// Showroom option packs (tint, PPF, nano) have NO published retail price.

export type Grade = {
  id: string;
  name_en: string | null;
  name_ar: string | null;
  price_incl_vat_sar: number | null;
  price_ex_vat_sar: number | null;
  colours: string[];
};

export type Model = {
  id: string;
  name: string;
  year: string | null;
  starting_price_incl_vat_sar: number | null;
  grades: Grade[];
};

export const MODELS: Model[] = ${JSON.stringify(models)};

export function findModel(idOrName: string): Model | null {
  const q = String(idOrName ?? "").trim().toLowerCase();
  if (!q) return null;
  return (
    MODELS.find((m) => m.id.toLowerCase() === q) ??
    MODELS.find((m) => m.name.toLowerCase() === q) ??
    null
  );
}

export function findGrade(model: Model, idOrName: string): Grade | null {
  const q = String(idOrName ?? "").trim().toLowerCase();
  if (!q) return null;
  return (
    model.grades.find((g) => g.id.toLowerCase() === q) ??
    model.grades.find((g) => (g.name_en ?? "").toLowerCase() === q) ??
    model.grades.find((g) => (g.name_ar ?? "") === String(idOrName).trim()) ??
    null
  );
}
`;

const dest = join(here, "..", "..", "supabase", "functions", "_shared", "catalogue.ts");
writeFileSync(dest, out);
console.log("wrote", dest, `(${models.length} models)`);
